services:
  - type: web
    name: visitor-pass-management
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OTP_DEMO_MODE
        value: "true"
      - key: OTP_RESEND_SECONDS
        value: "10"
      - key: MONGO_DNS_SERVERS
        value: "1.1.1.1,8.8.8.8"
